const tableNames = {
  TABLE_NAME_USER_TYPES: "user_types",
  TABLE_NAME_USER_STATUS: "user_status",
  TABLE_NAME_USERS: "users",
  TABLE_NAME_USER_STATUS_LOGS: "user_status_logs",
  TABLE_NAME_BRAND_PROFILES: "brand_profiles",
  TABLE_NAME_INFLUENCER_PROFILES: "influencer_profiles",
  TABLE_NAME_WISHLISTS: "wishlists",
  TABLE_NAME_WISHLIST_ITEMS: "wishlist_items",
  TABLE_NAME_NOTIFICATIONS: "notifications",
  TABLE_NAME_PLATFORMS: "platforms",
  TABLE_NAME_SOCIAL_ACCOUNTS: "social_accounts",
  TABLE_NAME_CATEGORIES: "categories",
  TABLE_NAME_INFLUENCER_CATEGORIES: "influencer_categories",
  TABLE_NAME_PLANS: "plans",
  TABLE_NAME_SUBSCRIPTION_STATUS: "subscription_status",
  TABLE_NAME_BRAND_SUBSCRIPTIONS: "brand_subscriptions",
  TABLE_NAME_CAMPAIGN_STATUS: "campaign_status",
  TABLE_NAME_CAMPAIGNS: "campaigns",
  TABLE_NAME_PROPOSAL_STATUS: "proposal_status",
  TABLE_NAME_CAMPAIGN_PROPOSALS: "campaign_proposals",
  TABLE_NAME_ORDER_STATUS: "order_status",
  TABLE_NAME_ORDERS: "orders",
  TABLE_NAME_ORDER_STATUS_LOGS: "order_status_logs",
  TABLE_NAME_PAYMENT_STATUS: "payment_status",
  TABLE_NAME_PAYMENTS: "payments",
};

module.exports = tableNames;
